config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'logins/index'
 
  root 'logins#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :projects
  # resources :tasks
  resources :accounts do
    member do
      get :withdraw
      post :withdraw, to: "accounts#create_withdraw"
      get :transfer
      post :transfer, to: "accounts#create_transfer"
    end
    collection do
      get :deposit
      post :deposit, to: "accounts#create_deposit"
    end  
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  before_create :create_account_no
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :full_name, presence: true  
  validates :contact_no, numericality: {only_integer: true }

  has_many :transactions

  def create_account_no
    self.account_no = 12.times.map{rand(0..9)}.join    
  end  

  def self.withdrawal(user,balance,account_no)
    user.current_bal = (user.current_bal -= balance.to_f).round(2)
    user.save!
    debit = user.transactions.build
    debit.user_id = user.id
    debit.account_no = account_no
    debit.debit_amount = balance
    debit.credit_amount = 0.0
    debit.save!
  end

  def self.deposit(user,balance,account_no)
    user.current_bal = (user.current_bal += balance.to_f).round(2)
    user.save!
    credit = user.transactions.build
    credit.user_id = user.id
    credit.account_no = account_no
    credit.credit_amount = balance
    credit.debit_amount = 0.0
    credit.save!
  end 

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index 
    @transactions = Transaction.where(user_id: current_user.id)
  end	

  def create_deposit
    if params[:user][:current_bal].to_i <= 0
      flash[:error] = 'Transaction failed! Amount must be greater than 0.00'
      render :deposit
    else 
      @user = User.find_by_account_no(params[:user][:account_no])
      unless @user.blank?
        User.deposit(@user,params[:user][:current_bal],params[:user][:account_no])
        if current_user
          flash[:success] = "Money deposited successfully"
          redirect_to accounts_path
        else
          flash[:success] = "Money deposited successfully and Will get total balance in ammount field"
          render template: 'accounts/deposit' 
        end 
      else
        flash[:error] = "Invalid Account No."
        render :deposit
      end  
    end 
  end


  def create_withdraw
    if params[:user][:current_bal].to_i <= 0
      flash[:error] = 'Transaction failed! Amount must be greater than 0.00'
      render :withdraw
    else 
      @user = User.find(current_user.id) 
      if @user.current_bal <= 0
        flash[:error] = 'Transaction failed! No balance in your account please deposit first'
        render :transfer
      else 
        User.withdrawal(@user,params[:user][:current_bal],params[:user][:account_no])
        flash[:success] = "Money withdrawed successfully"
        redirect_to accounts_path
      end
    end
  end


  def create_transfer
    if params[:user][:current_bal].to_i <= 0
      flash[:error] = 'Transaction failed! Amount must be greater than 0.00'
      render :transfer
    else
      current_user_account = User.find(current_user.id)
      if current_user_account.current_bal <= 0
        flash[:error] = 'Transaction failed! No balance in your account please deposit first'
        render :transfer
      else  
        recipient_account = User.find_by_account_no(params[:user][:account_no])
        User.withdrawal(current_user_account,params[:user][:current_bal],current_user_account.account_no)
        User.deposit(recipient_account,params[:user][:current_bal],params[:user][:account_no])
        flash[:success] = "Money transfered successfully"
        redirect_to accounts_path
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name,:contact_no,:account_no,:current_bal])
  devise_parameter_sanitizer.permit(:account_update, keys: [:full_name,:contact_no,:account_no,:current_bal])
end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def index
  	 if user_signed_in?
  		redirect_to accounts_path
  	 else
  	     render :index
  	 end    			
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def header(text)
        content_for(:header) { text.to_s }
    end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/accounts/deposit.html.erb
<% header "Deposit" %>

<%= form_for :user do |f| %>

  <div class="form-group">
    <%= f.label :account_no %>
    <%= f.text_field :account_no  %>
  </div>

  <div class="form-group">
    <%= f.label :Enter_Ammount %>
    <%= f.text_field :current_bal %>
  </div>




  <%= f.submit "Save", class: 'btn btn-primary' %>
<% end %>

app/views/accounts/index.html.erb
<%= link_to 'Deposit Money', deposit_accounts_path, class: 'btn btn-primary btn-lg' %>
        
        
<%= link_to 'Withdraw Money', withdraw_account_path(current_user.id), class: 'btn btn-primary btn-lg' %>

<%= link_to 'Transfer Money', transfer_account_path(current_user.id), class: 'btn btn-primary btn-lg' %>
        
<h1>All Transactions</h1>      
<table class="table table-striped">
  <thead>
  <tr>
    <th>Account No</th>
    <th>Credit Ammount</th>
    <th>Debit Ammount</th>
    <th>Transaction Date</th>
  </tr>
</thead>
<tbody>
<% unless @transactions.blank?%>  
<% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.account_no %></td>
    <td><%= transaction.credit_amount %></td>
    <td><%= transaction.debit_amount %></td>
    <td><%= transaction.updated_at %></td>
  </tr>
<% end %>
<% else %>
<tr><td>No Records</td></tr>
<% end%>
</tbody>
</table>

app/views/accounts/transfer.html.erb
<% header "Transfer Ammount" %>

<%= form_for :user do |f| %>

  <div class="form-group">
    <%= f.label :account_no %>
    <%= f.text_field :account_no %>
  </div>

  <div class="form-group">
    <%= f.label :Enter_Ammount %>
    <%= f.text_field :current_bal %>
  </div>




  <%= f.submit "Save", class: 'btn btn-primary' %>
<% end %>

app/views/accounts/withdraw.html.erb
<% header "Withdrawal" %>

<%= form_for :user do |f| %>

  <div class="form-group">
    <%= f.label :account_no %>
    <%= f.text_field :account_no %>
  </div>

  <div class="form-group">
    <%= f.label :Enter_ammount %>
    <%= f.text_field :current_bal %>
  </div>


  <%= f.submit "Save", class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewApp</title>
    <%#= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

 <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Bank Account Management</a>
    </div>
    
    <ul class="nav navbar-nav navbar-right">
      <% unless user_signed_in? %>
        <li><a href="<%= new_user_registration_path %>"><span class="glyphicon glyphicon-user"></span> Create User Account</a></li>
        <li><a href="<%= new_user_session_path%>"><span class="glyphicon glyphicon-log-in"></span> Account Login</a></li>
        <% else %>
           <li><a>Welcome!&nbsp;<span class="glyphicon glyphicon-user"></span> <%= current_user.full_name %></a></li>
          <li><%= link_to 'Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :get %></li>
      <% end %>
    </ul>
  </div>
</nav> 



<%= yield :top_content %>

<div class="container">
    <h1><%= yield :header %></h1>
  <%= yield %>
</div>
  </body>
</html>

app/views/logins/index.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
    <% if user_signed_in?%>  	
        <h1>Welcome!</h1>
        <p>
            <%= link_to 'Deposit Money', deposit_account_path(current_user.id), class: 'btn btn-primary btn-lg' %>
        </p>
        <p>
            <%= link_to 'Withdraw Money', withdraw_account_path(current_user.id), class: 'btn btn-primary btn-lg' %>
        </p>
        
    <%else%>
        <p>Deposit Money From Here</p>
        <p>
            <%= link_to 'Deposit Money', deposit_accounts_path, class: 'btn btn-primary btn-lg' %>
        </p>
    <%end%>    
    </div>
  </div>
<% end %>